# .golangci.yml
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nilerr
    - noctx
    - paralleltest
    - perfsprint
    - revive
    - wsl
  settings:
    decorder:
      dec-order:
        - const
        - var
        - type
        - func
      disable-dec-order-check: false
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    mnd:
      ignored-functions:
        - klog.V
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
        - name: add-constant
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(

issues:
  max-issues-per-linter: 100
  max-same-issues: 100
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$