# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mexc_bot_postgres
    environment:
      POSTGRES_DB: mexc_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/postgres/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped

volumes:
  postgres_data: